# frontend/Dockerfile
FROM node:18

# Set working directory
WORKDIR /app

# Copy the frontend package.json and package-lock.json
COPY package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend files
COPY . .

# Expose frontend port
EXPOSE 5173

# Start the frontend server
CMD ["npm", "run", "dev"]
