version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Wait for the backend to start before launching the frontend
    depends_on:
      - backend
