name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        run: |
          docker build ./backend -f ./backend/DockerFile -t backend:test

      - name: Build frontend image
        run: |
          docker build ./frontend -f ./frontend/DockerFile -t frontend:test

      - name: Test backend container
        run: |
          docker run --rm -p 5000:5000 backend:test node server.js & sleep 5 && curl http://localhost:5000

      # - name: Test frontend container
      #   run: |
      #     docker run --rm -p 5173:5173 frontend:test npm run dev
      
      - name: Test full application with docker-compose
        run: |
          docker compose up -d
          sleep 30 # Czekaj na uruchomienie usług
          curl -f http://localhost:5001
          curl -f http://localhost:5173
        env:
          REACT_APP_BACKEND_URL: http://backend:5000

      # Tear down containers after tests
      - name: Tear down
        run: docker compose down
